### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by venerakanybekova** [venerakanybekova/student.kg#6]
Create use cases according to user stories

**Comment by venerakanybekova** [comment]
@venerakanybekova goof it is working, now each time someone makes changes in repository we will be notified in this chat

**Comment by karybekov22** [comment]
![Use Case Diagram1](https://user-images.githubusercontent.com/55115453/68866551-cb554d80-071e-11ea-8bad-9d3325194a1b.jpg)
